#!/bin/bash

#: Title       : create_reminder
#: Date        : Feb 24 2022
#: Author      : Nikola Velinov
#: Version     : 1.0
#: Description : Reads from standard input and appends reminders in a reminder file
#: Options     : None

#Store the user input as a variable
#Loop through the current directory to see if the reminders.txt file exists
#If the file doesn't exist, create the reminders file
#If the file exists, append stdin to the reminders file

REMINDER=$*

for file in $HOME; do
        if [ "$file" == ".reminders" ]; then
                break
        else
                touch "$HOME/.reminders"
                break
        fi
done

echo "$REMINDER" >> "$HOME/.reminders"
