#!/bin/bash

#: Title       : read_reminder
#: Date        : Feb 24 2022
#: Author      : Nikola Velinov
#: Version     : 1.0
#: Description : Reads reminders from the reminder file
#: Options     : -f, followed by a keyword to search in the reminder file

#Check to see if the user has included the -f option
#If the option is not included, read the file line by line
#Use the grep command to search the reminder file
#If the option is included, search the file and output the results
#Store the user input as a variable
#Loop through the home directory to see if the .reminders file exists
#If the file doesn't exist, create the reminders file
#If the file exists, append stdin to the reminders file

default() {

	echo "Usage: ${0} [-f SEARCH TERM IN REMINDERS FILE] || [REMINDER TEXT]  "
	echo "Additionally, you can run the script without positional parameters to enter interactive mode"
	echo "This script stores reminders in a reminders file, and allows the user to search their reminders"
}


while getopts f:h OPTION
do
	case ${OPTION} in
		f)
			cat "$HOME/.reminders" | grep ${OPTARG} | less
			exit 1
			;;
		h)
			default
			exit 0
			;;
		*)
			cat "$HOME/.reminders" | less 
			exit 1
			;;
	esac
done 2> /dev/null


shift $((OPTIND -2)) 2> /dev/null

REMINDER=$*

for file in $HOME; do
        if [ "$file" == ".reminders" ]; then
                break
        else
                touch "$HOME/.reminders"
                break
        fi
done

echo "$REMINDER" >> "$HOME/.reminders"

if [ ! $1 ] || [ $# -lt 1 ]; then
	echo "Entering interactive mode, press Ctrl+D to exit."
	input=""
	while read line
	do
	input="$input\n$line"
	done
fi

echo -ne "$input" >> "$HOME/.reminders"

exit 0
