#!/bin/bash
#: Title       : replace_file_spaces 
#: Date        : Feb 23 2022
#: Author      : Nikola Velinov
#: Version     : 1.0
#: Description : Renames all files in a directory or file with spaces in their name with an underscore or a hyphen
#: Options     : -c, followed by the character to replace spaces with (hyphen or underscore)

#Using conditional statements, determine if the user's input is a file or directory
#If it is a directory, loop through all of the files in the directory
#Using conditional statements, check if the user has included the optional "-c" option
#Check using conditional statements if the user wants spaces to be replaced with an underscore or hyphen
#Use the mv command to rename files

determine_special_character() {
	if [[ ${OPTARG} == "-" ]]
	then
		echo "A hyphen has been set as the special character" >&2
		SPECIAL_CHARACTER="-"
		echo $SPECIAL_CHARACTER
		exit 0
	elif [[ ${OPTARG} == "_" ]]  
	then
		echo "An underscore has been set as the special character" >&2
		SPECIAL_CHARACTER="_"
		echo $SPECIAL_CHARACTER
		exit 0
	fi
}

default() {
	echo "Usage: $0 [-c CHARACTER TO REPLACE SPACES WITH] [FILE OR DIRECTORY] "
	echo "Replaces spaces in a file or directory with the desired character"
	exit 1
}

rename_file() {
	mv "$1" "${1// /$2}" 2> /dev/null
	echo "File has been successfully renamed" 
}

while getopts c:h OPTION
do
	case ${OPTION} in 
		c)
			SPECIAL_CHARACTER="$(determine_special_character)"
			;;
		h)
			default
			;;
	esac 
done 

if [ $OPTIND -eq 1 ] 
then 
	SPECIAL_CHARACTER="_"
	echo "The -c option was not included so $SPECIAL_CHARACTER has been set as the special character"
fi

shift $((OPTIND -1))
FILEDIR=$1

if [[ -f $FILEDIR ]]
then
	rename_file "$FILEDIR" $SPECIAL_CHARACTER
fi

if [[ -d $FILEDIR ]]
then 
	for file in $FILEDIR/*

	do
		rename_file "$file" $SPECIAL_CHARACTER
		if [[ -d $file ]]
		then
			for files in $file/*
			do
				rename_file "$files" $SPECIAL_CHARACTER
			done
		fi

	done
fi

exit 0
